---

- name: Installing package on apt based systems
  apt:
    name: '{{ item }}'
    state: 'present'
  when: ansible_pkg_mgr == 'yum'
  with_items: sudo_package

- name: Installing package on yum/rpm based systems
  yum:
    name: '{{ item }}'
    state: 'present'
  when: ansible_os_family == "RedHat"
  with_items: sudo_package
